# Generated by Django 3.0 on 2021-07-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='area',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
