# Generated by Django 3.0 on 2021-07-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210703_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Property_Kind',
            field=models.CharField(max_length=100),
        ),
    ]
