# Generated by Django 3.0 on 2021-07-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210703_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Price',
            field=models.TextField(),
        ),
    ]
