# Generated by Django 3.0 on 2021-07-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210703_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Image1',
            field=models.ImageField(blank=True, default='', null='', upload_to='Property_Images/'),
        ),
        migrations.AlterField(
            model_name='area',
            name='Image2',
            field=models.ImageField(blank=True, default='', null='', upload_to='Property_Images/'),
        ),
        migrations.AlterField(
            model_name='area',
            name='Image3',
            field=models.ImageField(blank=True, default='', null='', upload_to='Property_Images/'),
        ),
        migrations.AlterField(
            model_name='area',
            name='Image4',
            field=models.ImageField(blank=True, default='', null='', upload_to='Property_Images/'),
        ),
        migrations.AlterField(
            model_name='area',
            name='Image5',
            field=models.ImageField(blank=True, default='', null='', upload_to='Property_Images/'),
        ),
    ]
