# Generated by Django 3.0 on 2021-07-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210704_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
